stories_app/routes.py
import time
from typing import List, Tuple
from flask import render_template, request, url_for
from flask import Blueprint
from sqlalchemy import func, and_
from datetime import datetime
from sqlalchemy.orm import aliased
from stories_app.db import db

from stories_app.models import Story, StoryCategory, StoryRating

from prometheus_client import Counter, Histogram, generate_latest, REGISTRY

routes = []

requests_total = Counter("stories_requests_total", "Total HTTP Requests")
request_duration = Histogram(
    "stories_request_duration_seconds", "Request latency in seconds"
)


bp = Blueprint("stories", __name__)


@bp.route("/")
def index():
    start_time = time.time()
    requests_total.inc()
    top_rated = Story.top_rated(20)
    end_time = time.time()
    request_duration.observe(end_time - start_time)
    categories = StoryCategory.query.distinct(StoryCategory.category).all()

    unique_model_names = db.session.query(Story.model_name).distinct().all()
    unique_model_names = [result[0] for result in unique_model_names]

    return render_template(
        "index.html",
        top_rated=top_rated,
        categories=categories,
        models=unique_model_names,
    )


@bp.route("/about")
def about():
    requests_total.inc()
    return render_template("about.html")


@bp.route("/story/<uuid:id>")
def story(id):
    requests_total.inc()
    story = Story.query.filter_by(id=id).first()
    return render_template("story.html", story=story)


@bp.route("/stories")
def stories():
    start_time = time.time()
    requests_total.inc()

    page = request.args.get("page")
    per_page = request.args.get("per_page")
    model_name = request.args.get("model_name")
    created_at = request.args.get("created_at")
    updated_at = request.args.get("updated_at")
    categories = request.args.get("categories")
    ratings = request.args.get("ratings")
    title = request.args.get("title")
    length = request.args.get("length")

    if page:
        page = int(page)
    else:
        page = 1

    if per_page:
        per_page = int(per_page)
    else:
        per_page = 30
    per_page = min(per_page, 200)

    # story = Story.query.paginate(page, per_page)
    story_query = Story.query
    if model_name:
        story_query = story_query.filter(Story.model_name == model_name)

    if created_at:
        created_at_date = datetime.strptime(created_at, "%Y-%m-%d")
        story_query = story_query.filter(func.date(Story.created_at) == created_at_date)

    if updated_at:
        updated_at_date = datetime.strptime(updated_at, "%Y-%m-%d")
        story_query = story_query.filter(func.date(Story.updated_at) == updated_at_date)

    if categories:
        # Assuming categories are passed as a list of strings separated by commas
        category_list = categories.split(",")

        for category_name in category_list:
            category_alias = aliased(StoryCategory)
            story_query = story_query.join(category_alias, Story.categories).filter(
                category_alias.category == category_name
            )

    if ratings:

        # if ratings includes a -, assume it's a range
        if "-" in ratings:
            low, high = ratings.split("-")
            if low > high:
                low, high = high, low  # Swap values to ensure low is the smallest
            rating_list = [*range(int(low), int(high) + 1)]
        else:
            # Assuming ratings are passed as a list of integers separated by commas
            rating_list = [int(rating) for rating in ratings.split(",")]
        story_query = story_query.join(Story.ratings).filter(
            StoryRating.rating.in_(rating_list)
        )

    if title:
        story_query = story_query.filter(Story.title.ilike(f"%{title}%"))

    if length:
        story_query = story_query.filter(Story.length == length)

    if page and per_page:
        story_query = story_query.limit(per_page).offset((page - 1) * per_page)

    stories = story_query.all()

    # FIXME: This is in memory and could probs be done in the db
    categories_param_name = "categories"
    unique_categories = set()
    for story in stories:
        for category in story.categories:
            unique_categories.add(category.category)
    categories: List[
        Tuple[str, str, bool]
    ] = (
        []
    )  # a list of "categories" - which involves a name, the url, and whether this category has already been applied
    for category in list(unique_categories):
        category_is_applied_already = False
        existing_query_params = request.args.copy()
        if categories_param_name in existing_query_params:
            # remove the category if it exists and it gets clicked on
            if category in existing_query_params[categories_param_name]:
                category_is_applied_already = True
                existing_query_params[categories_param_name] = (
                    existing_query_params[categories_param_name]
                    .replace(category, "")
                    .replace(",,", ",")
                    .strip(",")
                )
                if len(existing_query_params[categories_param_name]) == 0:
                    del existing_query_params[categories_param_name]
            else:
                # ?category exists, but the specific category we're looking at (eg. 'funny') doesn't already exist on that line
                if category == "":
                    del existing_query_params[categories_param_name]
                else:
                    existing_query_params[categories_param_name] = (
                        existing_query_params[categories_param_name] + "," + category
                    )

        else:
            # If it ?categories doesn't exist, add it with the new value
            existing_query_params[categories_param_name] = category

        url = url_for("stories.stories", **existing_query_params)
        categories.append((category, url, category_is_applied_already))

        # Generate the updated URL with the modified query parameters
        # updated_url = url_for(request.endpoint, **existing_query_params)

        # if "categories" in existing_query_params:
        #     url = url.replace(existing_query_params["categories"], category)

    categories = sorted(categories, key=lambda x: x[0])  # sort by name first
    categories = sorted(
        categories, key=lambda x: x[2], reverse=True
    )  # sort by whether the category is applied already

    end_time = time.time()
    request_duration.observe(end_time - start_time)
    return render_template("stories.html", stories=stories, categories=categories)


@bp.route("/random-story")
def random_story():
    requests_total.inc()
    s = Story.get_random()
    return render_template("story.html", story=s)


@bp.route("/metrics")
def metrics():
    return generate_latest(REGISTRY)

stories_app/templates/about.html
{% extends "layout.html" %}


{% block body %}
<h1 class="center">About</h1>
<main class="main-content">
  <p>I tried to get a load of different AI models to generate a load of different stories.</p>
  <p>I also tried getting the models to rate the stories... but that's not especially good.</p>
  <p>Maybe this will improve as I get better at making models that can write or review stories ¯\_(ツ)_/¯</p>
  <br />
</main>







{% endblock %}

stories_app/templates/index.html
{% extends "layout.html" %}


{% block body %}
<h1 class="center">📚 AI-generated short stories</h1>
<div class="right-sidebar-grid">
    <main class="main-content">
    <ul>
        <li>
            <a href="{{ url_for("stories.about") }}">About Us</a>
        </li>
        <li>
            <a href="{{ url_for("stories.random_story") }}">Random story</a>
        </li>
        <li>
            <a href="/">Index <i class="fa fa-caret-right"></i></a>
        </li>
    </ul>
    <br/>
    <container>
      <h2>Top AI-rated stories</h2>
        <ul>
            {% for story in top_rated %}
                <li>
                    <a href="{{ url_for('stories.story', id=story.id) }}">
                        <strong>{{ story.average_rating() |int }}%</strong> - {{ story.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </container>

    </main>
    <section class="right-sidebar">
        <h4>Categories</h4>

        <ul>
        {% for category in categories %}
            <li> <a href="{{ url_for('stories.stories', categories=category.category) }}">{{ category.category }}</a></li>
        {% endfor %}
        </ul>

        <h4>Models</h4>
        <ul>
        {% for model in models %}
            <li> <a href="{{ url_for('stories.stories', model_name=model) }}">{{ model }}</a></li>
        {% endfor %}
        </ul>

    </section>
</div>







{% endblock %}

stories_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">

  {% block title %}
  <title>📚ShortStories📚</title>
  {% endblock %}
  <title>FlaskApp</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <meta name="viewport" content="width=device-width, initial-scale=1">



</head>

<body>

  {% block nav %}
  <nav class="container navbar navbar-light navbar-expand-sm">
    {% include 'nav.html' %}
  </nav>
  {% endblock %}
  {% block body %}
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <a href="{{ url_for('stories.about') }}">About Us</a>
  <a href="{{ url_for('stories.random_story') }}">Random story</a>
  {% endblock %}

</body>

</html>

stories_app/templates/nav.html
<span class="navbar-brand">
  📚
  <a class="navbar-brand" href="/">
    ShortStories.lol
  </a>
</span>

<div class="login">
  Maybe log in or something (WIP!)
</div>

stories_app/templates/stories.html
{% extends "layout.html" %}
{% block body %}
    <div class="right-sidebar-grid">
        <header class="header">
            <h1>Stories (maybe include categories here?)</h1>
        </header>
        <main class="main-content">
            {% for story in stories %}
                <article class="story">
                    <a href="{{ url_for('stories.story', id=story.id) }}">{{ story.average_rating() |int }}% - {{ story.title }}</a>
                </article>
            {% endfor %}
        </main>
        <section class="right-sidebar">
            <ul>
                <li>
                    <a href="{{ url_for("stories.stories") }}">Clear Filter</a>
                </li>
                {% for (category, url, is_applied) in categories %}
                    <li class="{% if is_applied %}is-applied{% endif %}">
                        <a href="{{ url }}">{{ category }}</a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    </div>
{% endblock %}

stories_app/templates/story.html
{% extends "layout.html" %}


{% block title %}
<title>📚ShortStories📚 - {{story.title}}</title>
{% endblock %}

{% block body %}


<div class="right-sidebar-grid">
    <header class="header">  
      <h1>{{ story.title }}</h1>
    </header>
    <main class="main-content">
      {{ story.text }}
    </main>
    <section class="right-sidebar">
      {% if story.ratings|length > 0 %}
        <h4>Ratings</h4>
        <ul>
          {% for rating in story.ratings %}
          <li>{{ rating}}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {% if story.categories|length > 0 %}
        <h4>Categories</h4>
        <ul>
        {% for category in story.categories %}
            <li> <a href="{{ url_for('stories.stories', categories=category.category) }}">{{ category }}</a></li>
        {% endfor %}
        </ul>
      {% endif %}

      <h4>Proposed Length: {{ story.length }}<h4>
          <h4>Model: <a href="{{ url_for('stories.stories', model_name=story.model_name) }}">{{ story.model_name }}</a></h4>
      <h4>Created At: {{ story.created_at }}</h4>



    <label for="show-text">Click to see prompt:</label>
    <input type="checkbox" id="show-text">
    <div id="hidden-content">
            <h4> Prompt </h4>
            
            
            {{ story.prompt }}
    </div>



    </section>
</div>







{% endblock %}